# Permalinks
permalink:           pretty

# Setup
title:               Mandi Gerth
tagline:             Teacher. Writer. Speaker.
url:                 https://mandigerth.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mandi Gerth
  url:               https://twitter.com/mandigerth
  email:             gerth@uwalumni.com

# Custom vars
version:             2.0.1
github:
  repo:              https://github.com/mandigerth/site
# google_analytics:    UA-3363703-15
twitter:             mandigerth
github:              mandigerth

# Gems
plugins:
  # - jekyll-paginate
  # - jekyll-gist
